more progress - not tested

diff --git a/ec2_with_external_signal/ec2_with_signal.yml b/ec2_with_external_signal/ec2_with_signal.yml
--- a/ec2_with_external_signal/ec2_with_signal.yml
+++ b/ec2_with_external_signal/ec2_with_signal.yml
@@ -86,10 +86,10 @@ Parameters:
   RuleState:
     Type: String
     AllowedValues:
-      - Enabled
-      - Disabled
-    Default: Enabled
-    Description: "A parameter that can only have the value 'Enabled', 'Disabled'"
+      - enabled
+      - disabled
+    Default: enabled
+    Description: "A parameter that can only have the value 'enabled', 'disabled'"
 
   Threshold:
     Type: Number
@@ -233,6 +233,21 @@ Resources:
           #sudo systemctl restart cfn-hup
 
           yum update -y aws-cfn-bootstrap
+
+          # Check if stack is in CREATE_IN_PROGRESS state
+          stack_status=$(aws cloudformation describe-stacks --stack-name ${AWS::StackName} --query "Stacks[0].StackStatus" --output text 2>&1)
+          if [[ $? -ne 0 ]]; then
+            echo "Failed to describe stack. Error: $stack_status"
+            stack_status="DENIED"
+          fi
+
+          if [[ "$stack_status" == "CREATE_IN_PROGRESS" ]]; then
+            echo "Stack is in CREATE_IN_PROGRESS state. Sending cfn-init signal."
+            /opt/aws/bin/cfn-init -s true --stack ${AWS::StackId} --resource EC2Instance --region ${AWS::Region}
+          elif [[ "$stack_status" == "DENIED" || "$stack_status" == *"IN_PROGRESS" ]]; then
+            echo "Stack status is DENIED or UPDATE_IN_PROGRESS. Exiting with success (letting signal be handled externally)"
+            exit 0
+
           # Start cfn-init
           echo "userdata script: start cfn-init. log files: /var/log/cloud-init.log , /var/log/cloud-init-output.log, /var/log/cfn-init-cmd.log , /var/log/cfn-init.log "
           # /opt/aws/bin/cfn-init -v -s ${AWS::StackId} -r EC2Instance --region ${AWS::Region} --configsets init_setup || error_exit 'Failed to run cfn-init'
@@ -276,8 +291,7 @@ Resources:
     Type: 'Custom::MyCustomResource'
     Properties:
       ServiceToken: !GetAtt CFSignalerFunctionRole.Arn
-      ParameterValue: !Ref Threshold
-      Counter: !Ref SchedulerSSMParameter
+      SchedulerSSMParameter: !Ref SchedulerSSMParameter
 
   CFSignalerFunctionRole:
     Type: AWS::IAM::Role
@@ -316,6 +330,12 @@ Resources:
       Handler: app.lambda_handler
       Runtime: python3.10
       Timeout: 240
+      Environment:
+        Variables:
+          LogicalResourceId: "EC2Instance" # is the CF logical name of ec2instance
+          SchedulerName: "CFSignalerRule"
+          Threshold: !Ref Threshold
+          
       # Layers:
       #   - !Ref Layer
 
@@ -335,7 +355,7 @@ Resources:
               "ResourceProperties": {
                 "StackName": "${AWS::StackName}",
                 "Event":"CFSignalerRule",
-
+                "SchedulerSSMParameter": ${SchedulerSSMParameter}
               }
             }
 
@@ -352,7 +372,7 @@ Resources:
     Properties:
       Name: !Sub "${AWS::StackId}/CFSignalerFunction/SchedulerFlag"
       Type: "String"
-      Value: !Sub "RuleState_increment_0"
+      Value: !Sub "${RuleState}_increment_0"
       Description: "This parameter is used to store a the scheduler state"
 
 Outputs:
